source 'https://rubygems.org'
gem 'cocoapods', '~>1'
gem 'xcodeproj', '~>1'
gem 'fastlane', '~>1'
gem 'match', '~>0'
gem 'pilot', '~>1'
gem 'scan', '~>0'
gem 'plist', '~>3'
gem 'spaceship', '~>0.31'
gem 'CFPropertyList', '2.3.2'
gem 'sqlite3', '1.3.11'
gem 'activesupport', '~>4.0'
gem 'houston'
gem 'danger'
gem 'danger-prose'
gem 'danger-xcov'
gem 'danger-todoist'
gem 'danger-swiftlint'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
